# Generated by Django 2.1.4 on 2019-07-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用戶名稱')),
                ('fbid', models.CharField(max_length=50, verbose_name='FB ID')),
                ('user_profile_url', models.URLField(verbose_name='FB url')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否為管理員')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, max_length=200, verbose_name='地址')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='程式')),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='電話')),
                ('invoice_id', models.CharField(blank=True, max_length=50, verbose_name='發票號碼')),
                ('invoice_title', models.CharField(blank=True, max_length=100, verbose_name='發票抬頭')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_fb_link', models.URLField(blank=True, verbose_name='FB po文時間')),
                ('amount', models.IntegerField(verbose_name='數量')),
                ('commented_at', models.DateTimeField(blank=True, verbose_name='留言時間')),
                ('is_confrimed', models.BooleanField(default=False, verbose_name='是否確認訂單')),
                ('canceled', models.BooleanField(default=False, verbose_name='是否取消')),
                ('confirm_at', models.DateTimeField(blank=True, verbose_name='確認訂單時間')),
                ('fb_comment_content', models.TextField(verbose_name='留言內文')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新時間')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, max_length=50, verbose_name='產品ID')),
                ('wine_id', models.CharField(max_length=20)),
                ('erp_no', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=200, verbose_name='產品名稱')),
                ('quantity', models.IntegerField(blank=True, verbose_name='數量')),
                ('price', models.IntegerField(blank=True, verbose_name='價錢')),
                ('available', models.BooleanField(default=True, verbose_name='上架')),
                ('post_time', models.DateTimeField(blank=True, verbose_name='創建時間')),
                ('available_at', models.DateTimeField(blank=True, verbose_name='上架時間')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='修改時間')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='fbCrawler.Product'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='fbCrawler.Members'),
        ),
    ]
