# Generated by Django 2.1.4 on 2019-07-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='members',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='程式'),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='發票號碼'),
        ),
        migrations.AlterField(
            model_name='members',
            name='invoice_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='發票抬頭'),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='members',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='commented_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='留言時間'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上架時間'),
        ),
        migrations.AlterField(
            model_name='product',
            name='erp_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='產品ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='post_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='價錢'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='數量'),
        ),
    ]
