# Generated by Django 2.1.4 on 2019-07-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0002_auto_20190722_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='month',
            field=models.IntegerField(null=True, verbose_name='上架月份'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_fb_link',
            field=models.URLField(blank=True, null=True, verbose_name='FB Post 連結'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(null=True, verbose_name='上架年份'),
        ),
    ]
