# Generated by Django 2.1.4 on 2019-07-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0003_auto_20190722_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='html',
            field=models.TextField(blank=True, null=True, verbose_name='HTML 檔案'),
        ),
    ]
