# Generated by Django 2.0.6 on 2019-07-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0004_product_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='comment_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='留言順序'),
        ),
    ]
