# Generated by Django 2.0.6 on 2019-07-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0005_orders_comment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='confirm_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='確認訂單時間'),
        ),
    ]
