# Generated by Django 2.0.6 on 2019-07-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0006_auto_20190725_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='member',
        ),
    ]
