# Generated by Django 2.0.6 on 2019-08-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0007_auto_20190725_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='區'),
        ),
        migrations.AlterField(
            model_name='members',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='城市'),
        ),
    ]
