# Generated by Django 2.0.6 on 2019-08-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0008_auto_20190819_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='shipname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='收件人'),
        ),
    ]
