# Generated by Django 2.0.6 on 2019-08-20 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0009_members_shipname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='小幫手名稱')),
                ('fbid', models.CharField(max_length=50, verbose_name='小幫手 Fb id')),
                ('user_profile_url', models.URLField(verbose_name='小幫手 FB url')),
                ('work_percent', models.IntegerField(verbose_name='小幫手工作比例')),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='helper',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fbCrawler.Helper'),
        ),
    ]
