# Generated by Django 2.0.6 on 2019-08-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0010_auto_20190820_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='confirm_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='結算完數量'),
        ),
        migrations.AddField(
            model_name='orders',
            name='session',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='團次編號'),
        ),
        migrations.AddField(
            model_name='product',
            name='order_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='購買數量限制'),
        ),
    ]
