# Generated by Django 2.0.6 on 2019-08-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0011_auto_20190826_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, verbose_name='團次編號')),
                ('is_self_take', models.BooleanField(default=False, verbose_name='上架')),
                ('year', models.IntegerField(null=True, verbose_name='團次年份')),
                ('month', models.IntegerField(null=True, verbose_name='團次月份')),
                ('price_before_disc', models.IntegerField(blank=True, null=True, verbose_name='折扣前總價')),
                ('price_after_disc', models.IntegerField(blank=True, null=True, verbose_name='直扣後總價')),
                ('ship_fee', models.IntegerField(blank=True, null=True, verbose_name='運費')),
                ('total_price', models.IntegerField(blank=True, null=True, verbose_name='含運費價錢')),
                ('member', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='fbCrawler.Members')),
            ],
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='session',
            new_name='session_id',
        ),
    ]
