# Generated by Django 2.0.6 on 2019-08-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0013_members_is_self_take'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='bank_account_branch',
            field=models.CharField(blank=True, max_length=100, verbose_name='小幫手帳戶分行'),
        ),
        migrations.AddField(
            model_name='helper',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='小幫手帳戶號碼'),
        ),
        migrations.AddField(
            model_name='helper',
            name='bank_account_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='小幫手帳戶戶名'),
        ),
    ]
