# Generated by Django 2.0.6 on 2019-09-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0014_auto_20190826_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='session_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='團次編號'),
        ),
    ]
