# Generated by Django 2.0.6 on 2019-09-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0015_product_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='訂單編號')),
                ('ship_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='取貨方式')),
                ('price_before_disc', models.IntegerField(blank=True, null=True, verbose_name='折扣前總價')),
                ('price_after_disc', models.IntegerField(blank=True, null=True, verbose_name='直扣後總價')),
                ('ship_fee', models.IntegerField(blank=True, null=True, verbose_name='運費')),
                ('total_price', models.IntegerField(blank=True, null=True, verbose_name='含運費價錢')),
            ],
        ),
        migrations.CreateModel(
            name='DeliverRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='運費規則名稱')),
                ('commodity', models.CharField(blank=True, max_length=50, verbose_name='商品名稱')),
                ('deliver_rule1', models.IntegerField(blank=True, null=True, verbose_name='運費門檻 1')),
                ('deliver_rule1_price', models.IntegerField(blank=True, null=True, verbose_name='運費門檻 1 價錢')),
                ('deliver_rule2', models.IntegerField(blank=True, null=True, verbose_name='運費門檻 2')),
                ('deliver_rule2_price', models.IntegerField(blank=True, null=True, verbose_name='運費門檻 2 價錢')),
                ('deliver_rule3', models.IntegerField(blank=True, null=True, verbose_name='運費門檻 3')),
                ('deliver_rule3_price', models.IntegerField(blank=True, null=True, verbose_name='運費門檻 3 價錢')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='FB 社團名稱')),
                ('url', models.URLField(verbose_name='FB Group url')),
                ('group_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='社團代碼')),
            ],
        ),
        migrations.RemoveField(
            model_name='members',
            name='is_self_take',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='confirm_at',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_self_take',
        ),
        migrations.RemoveField(
            model_name='session',
            name='member',
        ),
        migrations.RemoveField(
            model_name='session',
            name='price_after_disc',
        ),
        migrations.RemoveField(
            model_name='session',
            name='price_before_disc',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ship_fee',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_price',
        ),
        migrations.AddField(
            model_name='members',
            name='join_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='加入社團時間'),
        ),
        migrations.AddField(
            model_name='orders',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='fbCrawler.Session'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='is_confrimed',
            field=models.BooleanField(default=False, verbose_name='是否購買到'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='member',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='fbCrawler.Members'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='session',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='fbCrawler.Session'),
        ),
        migrations.AddField(
            model_name='members',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fbCrawler.Group'),
        ),
        migrations.AddField(
            model_name='session',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fbCrawler.Group'),
        ),
    ]
