# Generated by Django 2.0.6 on 2019-09-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0016_auto_20190911_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fbCrawler.Session'),
        ),
    ]
