# Generated by Django 2.0.6 on 2019-09-11 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0017_auto_20190911_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='deliver_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fbCrawler.DeliverRule'),
        ),
    ]
