# Generated by Django 2.0.6 on 2019-09-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0020_remove_product_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product_fb_link',
        ),
        migrations.AddField(
            model_name='checkout',
            name='amount_payable',
            field=models.IntegerField(blank=True, null=True, verbose_name='應付價錢'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='delivery_batch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='出貨批次'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='ship_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='指定配送日期'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='ship_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='配送時段'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='transfer_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='帳號末五碼'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='fb_comment_content',
            field=models.TextField(blank=True, null=True, verbose_name='留言內文'),
        ),
    ]
