# Generated by Django 2.0.6 on 2019-09-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0021_auto_20190919_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='transfer_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='匯款時間'),
        ),
    ]
