# Generated by Django 2.0.6 on 2019-09-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0023_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='transfer_announcement',
            field=models.TextField(blank=True, null=True, verbose_name='匯款公告'),
        ),
        migrations.AddField(
            model_name='session',
            name='update_announcement',
            field=models.TextField(blank=True, null=True, verbose_name='開放清單公告'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('open', '進行中'), ('update_orders', '用戶更新訂單'), ('system_updating', '系統計算中'), ('checkout', '用戶匯款'), ('cloced', '已結團')], default='open', max_length=20, verbose_name='團次狀態'),
        ),
    ]
