# Generated by Django 2.0.6 on 2019-09-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0024_auto_20190920_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='fb_login_app_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FB 登入 App ID'),
        ),
    ]
