# Generated by Django 2.0.6 on 2019-09-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0027_auto_20190921_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='session_id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_article_link',
            field=models.URLField(blank=True, null=True, verbose_name='FB 備份連結（禁止抄襲社團）'),
        ),
        migrations.AddField(
            model_name='product',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fbCrawler.Session'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fb_link',
            field=models.URLField(blank=True, null=True, verbose_name='FB 原始 Po 文連結'),
        ),
    ]
