# Generated by Django 2.0.6 on 2019-09-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0028_auto_20190922_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverFreeAllRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('deilverFreeAll', models.CharField(max_length=100)),
                ('deilverFreeAllbottle', models.CharField(max_length=100)),
                ('discountAll', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='deliverSettleRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('commodityName', models.CharField(max_length=100)),
                ('deliverRule1', models.CharField(max_length=100)),
                ('deliverRule1Price', models.CharField(max_length=100)),
                ('deliverRule2', models.CharField(max_length=100)),
                ('deliverRule2Price', models.CharField(max_length=100)),
                ('deliverRule3', models.CharField(max_length=100)),
                ('deliverRule3Price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='settlementRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('wineID', models.CharField(max_length=100)),
                ('erpID', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('stockNum', models.CharField(max_length=100)),
                ('wineName', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('deliverFree', models.CharField(max_length=100)),
                ('sale', models.CharField(max_length=100)),
                ('limit', models.CharField(max_length=100)),
            ],
        ),
    ]
