# Generated by Django 2.0.6 on 2019-09-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0029_deliverfreeallrule_deliversettlerule_settlementrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='free_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='優惠贈送數量'),
        ),
        migrations.AddField(
            model_name='orders',
            name='minus_free_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='扣除贈送量後計價數'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='price_after_disc',
            field=models.IntegerField(blank=True, null=True, verbose_name='折扣後總價'),
        ),
    ]
