# Generated by Django 2.0.6 on 2019-09-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0032_auto_20190930_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, verbose_name='帳號')),
                ('transaction_date', models.DateField(verbose_name='交易日期')),
                ('transaction_time', models.TimeField(verbose_name='交易時間')),
                ('transaction_id', models.CharField(max_length=100, verbose_name='交易序號')),
                ('deposit_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='存匯代號')),
                ('deposit_amount', models.IntegerField(verbose_name='存入金額')),
                ('summary', models.CharField(blank=True, max_length=100, null=True, verbose_name='摘要')),
                ('notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='附註')),
                ('session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fbCrawler.Session')),
            ],
        ),
    ]
