# Generated by Django 2.0.6 on 2019-10-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0034_auto_20191002_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='helper_notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='小幫手備註'),
        ),
    ]
