# Generated by Django 2.0.6 on 2019-10-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbCrawler', '0035_auto_20191006_2351'),
        ('fbCrawler', '0035_checkout_helper_notes'),
    ]

    operations = [
    ]
