# Generated by Django 2.0.6 on 2019-09-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orginalBigSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wineID', models.CharField(max_length=100)),
                ('fbURL', models.URLField(blank=True)),
                ('comment_order', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('fbuid', models.CharField(max_length=100)),
                ('commentTime', models.CharField(max_length=100)),
                ('orderCount', models.CharField(max_length=100)),
                ('crawlDate', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
            ],
        ),
    ]
