# Generated by Django 2.0.6 on 2019-09-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_deliverfreeallrule_deliverrule_settlementrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementrule',
            name='erpID',
            field=models.CharField(default='NaN', max_length=100),
        ),
    ]
